### Example 1: Get JSON of all Displays
GET http://localhost:8080/display/all

### Example 2: Adding a Display to the Database
POST http://localhost:8080/display/add
Content-Type: application/x-www-form-urlencoded

brand=Phillips &
model=Tableux &
width=1920 &
height=1080 &
orientation=vertical &
filename=moon.jpg


### Example 3: Deleting a Display by ID
DELETE http://localhost:8080/display/delete/2


### Example 4: Download an image from the server
GET http://localhost:8080/image/download/moon.jpg

