### Example 1: Get JSON of all Displays
GET http://localhost:8080/display/all

### Example 2: Adding a Display to the Database
POST http://localhost:8080/display/add
Content-Type: application/x-www-form-urlencoded

macAddress=00:00:00:00:06 &
brand=Phillips &
model=Tableux &
width=1920 &
height=1080 &
orientation=vertical &
filename=flora.jpg

### Example 3: Deleting a Display by MAC
DELETE http://localhost:8080/display/delete/00:00:00:00:99

### Example 4: Download an image from the server
GET http://localhost:8080/image/download/moon.jpg

### Example 5: Initiate a Display with it's mac address
POST http://localhost:8080/display/initiate
Content-Type: application/x-www-form-urlencoded

macAddress=00:00:00:00:03 &
width=1920 &
height=1080

### Example 6: Get single Display based on MAC
GET http://localhost:8080/display/get/00:00:00:00:01

### Example 7: Delete image based on Filename
DELETE http://localhost:8080/image/delete/test_delete_image.jpg

### Example 8: Get all Events
GET http://localhost:8080/event/all

### Example 9: Get all Events for a specific Display
GET http://localhost:8080/event/all/00:00:00:00:04

### Example 10: Add a new Event
POST http://localhost:8080/event/add
Content-Type: application/json

{
  "title": "Meeting",
  "allDay": false,
  "start": "2024-12-12T08:00:00",
  "end": "2024-12-12T09:00:00",
  "displayImages": [
    {
      "displayMac": "00:00:00:00:04",
      "image": "screen1.jpg"
    },
    {
      "displayMac": "00:00:00:00:05",
      "image": "screen2.jpg"
    }
  ]
}


### Example 11: Update an Event
PUT http://localhost:8080/event/update/1
Content-Type: application/json

{
  "title": "Updated Meeting",
  "allDay": false,
  "start": "2024-12-12T10:30:00",
  "end": "2024-12-12T11:30:00",
  "displayImages": [
    {
      "displayMac": "00:00:00:00:04",
      "image": "updated_screen1.jpg"
    },
    {
      "displayMac": "00:00:00:00:05",
      "image": "updated_screen2.jpg"
    }
  ]
}

### Example 12: Delete an Event by ID
DELETE http://localhost:8080/event/delete/6

### Example 13: Confirm image switch Endpoint
POST http://localhost:8080/display/switch
Content-Type: application/x-www-form-urlencoded

macAddress=00:00:00:00:02 &
filename=flora.jpg

### Example 14: Get already registered Brands
GET http://localhost:8080/display/brands

### Example 15: Post Battery percentage of Display
POST http://localhost:8080/display/postBattery
Content-Type: application/x-www-form-urlencoded

macAddress=00:00:00:00:05 &
batteryPercentage=89

### Example 16: Create a new configuration
POST http://localhost:8080/config/post
Content-Type: application/json

{
  "wakeIntervalDay": 30,
  "wakeIntervalNight": 90,
  "leadTime": 10,
  "followUpTime": 5,
  "deleteAfterDays": 30
}

### Example 17: Get the current configuration
GET http://localhost:8080/config/get

### Test RRule
POST http://localhost:8080/recevent/add
Content-Type: application/json

{
  "start": "2025-12-12T08:00:00",
  "end": "2025-12-12T09:00:00",
  "rrule": "FREQ=DAILY;COUNT=5"
}

### Delete Recurrent Event
DELETE http://localhost:8080/recevent/delete/6959cbd2-2b20-4cfa-bbbc-4888e58cc13c